[package]
name = "infra"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared"}

httpw = { workspace = true }

opentelemetry = { version = "0.19.0" }
tracing = { version = "0.1.37" }
