version:  "2.1"

services: 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_MANAGEMENT_DEFAULT_USER=guest
      - RABBITMQ_MANAGEMENT_DEFAULT_PASS=guest
    networks:
      - compose

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=otel-newrelic
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/database/data
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
    networks:
      - compose

networks:
  compose:
    driver: bridge

volumes:
  postgres-data: